In [2]:
import numpy as np

In [5]:
array1=np.zeros(10)

In [8]:
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
array1.itemsize

8

In [ ]:
add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional

In [9]:
array2=np.arange(10,50)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
rewerce=array2[::-1]
rewerce

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [18]:
matrix=np.arange(9)
matrix_reshape=matrix.reshape((3,3))
matrix_reshape


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [20]:
eye=np.eye(3,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
values=np.arange(5)
matrix=np.tile(values,(5,1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [29]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [30]:
vector=np.random.rand(10)
sorted_vector=np.sort(vector)
sorted_vector

array([0.07297512, 0.11795365, 0.28519433, 0.29935887, 0.30097356,
       0.3843886 , 0.48994256, 0.84004361, 0.85734867, 0.92365155])