In [3]:
1+2


3

In [ ]:
import numpy as np

In [4]:
one_dim_array=np.arange(11)


In [5]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
one_dim_array[0::2]


array([ 0,  2,  4,  6,  8, 10])

In [13]:
array2=np.arange(20,31)

In [14]:
array2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [16]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])